/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWalletsRouteImport } from './routes/dashboard/wallets'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard/transactions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardWalletsIndexRouteImport } from './routes/dashboard/wallets/index'
import { Route as DashboardTransactionsIndexRouteImport } from './routes/dashboard/transactions/index'
import { Route as DashboardWalletsNewRouteImport } from './routes/dashboard/wallets/new'
import { Route as DashboardWalletsWalletIdRouteImport } from './routes/dashboard/wallets/$walletId'
import { Route as DashboardTransactionsNewRouteImport } from './routes/dashboard/transactions/new'
import { Route as DashboardTransactionsTransactionIdRouteImport } from './routes/dashboard/transactions/$transactionId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletsRoute = DashboardWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletsIndexRoute = DashboardWalletsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardWalletsRoute,
} as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTransactionsRoute,
  } as any)
const DashboardWalletsNewRoute = DashboardWalletsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardWalletsRoute,
} as any)
const DashboardWalletsWalletIdRoute =
  DashboardWalletsWalletIdRouteImport.update({
    id: '/$walletId',
    path: '/$walletId',
    getParentRoute: () => DashboardWalletsRoute,
  } as any)
const DashboardTransactionsNewRoute =
  DashboardTransactionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardTransactionsRoute,
  } as any)
const DashboardTransactionsTransactionIdRoute =
  DashboardTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => DashboardTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRouteWithChildren
  '/dashboard/wallets': typeof DashboardWalletsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/transactions/$transactionId': typeof DashboardTransactionsTransactionIdRoute
  '/dashboard/transactions/new': typeof DashboardTransactionsNewRoute
  '/dashboard/wallets/$walletId': typeof DashboardWalletsWalletIdRoute
  '/dashboard/wallets/new': typeof DashboardWalletsNewRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/wallets/': typeof DashboardWalletsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/transactions/$transactionId': typeof DashboardTransactionsTransactionIdRoute
  '/dashboard/transactions/new': typeof DashboardTransactionsNewRoute
  '/dashboard/wallets/$walletId': typeof DashboardWalletsWalletIdRoute
  '/dashboard/wallets/new': typeof DashboardWalletsNewRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/wallets': typeof DashboardWalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRouteWithChildren
  '/dashboard/wallets': typeof DashboardWalletsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/transactions/$transactionId': typeof DashboardTransactionsTransactionIdRoute
  '/dashboard/transactions/new': typeof DashboardTransactionsNewRoute
  '/dashboard/wallets/$walletId': typeof DashboardWalletsWalletIdRoute
  '/dashboard/wallets/new': typeof DashboardWalletsNewRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/wallets/': typeof DashboardWalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/wallets'
    | '/dashboard/'
    | '/dashboard/transactions/$transactionId'
    | '/dashboard/transactions/new'
    | '/dashboard/wallets/$walletId'
    | '/dashboard/wallets/new'
    | '/dashboard/transactions/'
    | '/dashboard/wallets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/transactions/$transactionId'
    | '/dashboard/transactions/new'
    | '/dashboard/wallets/$walletId'
    | '/dashboard/wallets/new'
    | '/dashboard/transactions'
    | '/dashboard/wallets'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/wallets'
    | '/dashboard/'
    | '/dashboard/transactions/$transactionId'
    | '/dashboard/transactions/new'
    | '/dashboard/wallets/$walletId'
    | '/dashboard/wallets/new'
    | '/dashboard/transactions/'
    | '/dashboard/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallets': {
      id: '/dashboard/wallets'
      path: '/wallets'
      fullPath: '/dashboard/wallets'
      preLoaderRoute: typeof DashboardWalletsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallets/': {
      id: '/dashboard/wallets/'
      path: '/'
      fullPath: '/dashboard/wallets/'
      preLoaderRoute: typeof DashboardWalletsIndexRouteImport
      parentRoute: typeof DashboardWalletsRoute
    }
    '/dashboard/transactions/': {
      id: '/dashboard/transactions/'
      path: '/'
      fullPath: '/dashboard/transactions/'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardTransactionsRoute
    }
    '/dashboard/wallets/new': {
      id: '/dashboard/wallets/new'
      path: '/new'
      fullPath: '/dashboard/wallets/new'
      preLoaderRoute: typeof DashboardWalletsNewRouteImport
      parentRoute: typeof DashboardWalletsRoute
    }
    '/dashboard/wallets/$walletId': {
      id: '/dashboard/wallets/$walletId'
      path: '/$walletId'
      fullPath: '/dashboard/wallets/$walletId'
      preLoaderRoute: typeof DashboardWalletsWalletIdRouteImport
      parentRoute: typeof DashboardWalletsRoute
    }
    '/dashboard/transactions/new': {
      id: '/dashboard/transactions/new'
      path: '/new'
      fullPath: '/dashboard/transactions/new'
      preLoaderRoute: typeof DashboardTransactionsNewRouteImport
      parentRoute: typeof DashboardTransactionsRoute
    }
    '/dashboard/transactions/$transactionId': {
      id: '/dashboard/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/dashboard/transactions/$transactionId'
      preLoaderRoute: typeof DashboardTransactionsTransactionIdRouteImport
      parentRoute: typeof DashboardTransactionsRoute
    }
  }
}

interface DashboardTransactionsRouteChildren {
  DashboardTransactionsTransactionIdRoute: typeof DashboardTransactionsTransactionIdRoute
  DashboardTransactionsNewRoute: typeof DashboardTransactionsNewRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
}

const DashboardTransactionsRouteChildren: DashboardTransactionsRouteChildren = {
  DashboardTransactionsTransactionIdRoute:
    DashboardTransactionsTransactionIdRoute,
  DashboardTransactionsNewRoute: DashboardTransactionsNewRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
}

const DashboardTransactionsRouteWithChildren =
  DashboardTransactionsRoute._addFileChildren(
    DashboardTransactionsRouteChildren,
  )

interface DashboardWalletsRouteChildren {
  DashboardWalletsWalletIdRoute: typeof DashboardWalletsWalletIdRoute
  DashboardWalletsNewRoute: typeof DashboardWalletsNewRoute
  DashboardWalletsIndexRoute: typeof DashboardWalletsIndexRoute
}

const DashboardWalletsRouteChildren: DashboardWalletsRouteChildren = {
  DashboardWalletsWalletIdRoute: DashboardWalletsWalletIdRoute,
  DashboardWalletsNewRoute: DashboardWalletsNewRoute,
  DashboardWalletsIndexRoute: DashboardWalletsIndexRoute,
}

const DashboardWalletsRouteWithChildren =
  DashboardWalletsRoute._addFileChildren(DashboardWalletsRouteChildren)

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRouteWithChildren
  DashboardWalletsRoute: typeof DashboardWalletsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRouteWithChildren,
  DashboardWalletsRoute: DashboardWalletsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
